
name: GROUP-MANAGER

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "mrjoker"

          replace: "groupcare"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Replaced new name'

          commit_options: '--no-verify'

          repository: https://github.com/LEGEND-VIVEK/GROUP-MANAGER.

          commit_user_name: LEGEND-VIVEK

          commit_user_email: legendxx08377@gmail.com
